{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 labels:
    {{- include "technology-api.labels" . | nindent 4 }}
 name: {{ template "technology-api.fullname" . }}
rules:
{{ toYaml .Values.rbac.role.rules }}
{{- end }}