{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 labels:
   {{- include "technology-api.labels" . | nindent 4 }}
 name: {{ template "technology-api.fullname" . }}
subjects:
- kind: ServiceAccount
 name: {{ template "technology-api.serviceAccountName" . }}
roleRef:
 kind: Role
 apiGroup: rbac.authorization.k8s.io
 name: {{ template "technology-api.fullname" . }}
{{- end }}